// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAsubYhT-EgIut1mNBIoqjsmuB9iQfuCs',
    appId: '1:106875158936:web:3ed1c14c1ca010c0b62bed',
    messagingSenderId: '106875158936',
    projectId: 'retrieve-me',
    authDomain: 'retrieve-me.firebaseapp.com',
    storageBucket: 'retrieve-me.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZz1FiUV-GaE9L22uyiieYW36h5iP00tQ',
    appId: '1:106875158936:android:cd04a18b8ec3d976b62bed',
    messagingSenderId: '106875158936',
    projectId: 'retrieve-me',
    storageBucket: 'retrieve-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvgqsJSXUdsuy3cTApKiNmZiKyoZI7_g',
    appId: '1:106875158936:ios:4a0909e3bfce3955b62bed',
    messagingSenderId: '106875158936',
    projectId: 'retrieve-me',
    storageBucket: 'retrieve-me.appspot.com',
    iosClientId: '106875158936-crekq3denfoplf602lg59j9fo17okm2r.apps.googleusercontent.com',
    iosBundleId: 'com.kais29.retrieveMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRvgqsJSXUdsuy3cTApKiNmZiKyoZI7_g',
    appId: '1:106875158936:ios:dddb3b93084d9675b62bed',
    messagingSenderId: '106875158936',
    projectId: 'retrieve-me',
    storageBucket: 'retrieve-me.appspot.com',
    iosClientId: '106875158936-v949vjjbj2ef67l3lb0iq5d91j7f4usl.apps.googleusercontent.com',
    iosBundleId: 'com.kais29.retrieveMe.RunnerTests',
  );
}
